# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_auto_20161202_1535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Course',
        ),
    ]
